"""0001 initial schema

Revision ID: 422c971fb1b1
Revises: 
Create Date: 2026-09-07 10:14:36.965381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422c971fb1b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycles',
    sa.Column('cycle', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('total_posts', sa.Integer(), nullable=False),
    sa.Column('total_recruits', sa.Integer(), nullable=False),
    sa.Column('score_unresolved', sa.Integer(), nullable=False),
    sa.Column('evidence_level', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('snapshot_date', sa.String(length=32), nullable=True),
    sa.Column('gaps', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cycle')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('cycle', sa.String(length=8), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('exam', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=256), nullable=True),
    sa.Column('zw', sa.String(length=256), nullable=True),
    sa.Column('zy', sa.Text(), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('xl', sa.String(length=64), nullable=True),
    sa.Column('xw', sa.String(length=64), nullable=True),
    sa.Column('xz', sa.String(length=64), nullable=True),
    sa.Column('age', sa.String(length=128), nullable=True),
    sa.Column('bz', sa.Text(), nullable=True),
    sa.Column('lb', sa.String(length=64), nullable=True),
    sa.Column('title_status', sa.String(length=32), nullable=True),
    sa.Column('display_title', sa.String(length=256), nullable=True),
    sa.Column('job_status', sa.String(length=32), nullable=True),
    sa.Column('score_observation_status', sa.String(length=32), nullable=True),
    sa.Column('score_observation_scale_id', sa.String(length=32), nullable=True),
    sa.Column('score_observation_value', sa.Numeric(), nullable=True),
    sa.Column('competition_metric_type', sa.String(length=32), nullable=True),
    sa.Column('competition_base', sa.Integer(), nullable=True),
    sa.Column('competition_source', sa.String(length=128), nullable=True),
    sa.Column('ratio_comparable', sa.Boolean(), nullable=True),
    sa.Column('source', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_city'), 'jobs', ['city'], unique=False)
    op.create_index(op.f('ix_jobs_code'), 'jobs', ['code'], unique=False)
    op.create_index(op.f('ix_jobs_cycle'), 'jobs', ['cycle'], unique=False)
    op.create_index(op.f('ix_jobs_exam'), 'jobs', ['exam'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_jobs_lb'), 'jobs', ['lb'], unique=False)
    op.create_table('review_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('cycle', sa.String(length=8), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=True),
    sa.Column('resolution_trigger', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_events_kind'), 'review_events', ['kind'], unique=False)
    op.create_index(op.f('ix_review_events_severity'), 'review_events', ['severity'], unique=False)
    op.create_table('salary_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('employment_type', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('value_wan', sa.Numeric(), nullable=True),
    sa.Column('snapshot_year', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'employment_type', 'stage', 'snapshot_year', name='uq_salary')
    )
    op.create_table('score_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle', sa.String(length=8), nullable=False),
    sa.Column('composite_key', sa.String(length=256), nullable=True),
    sa.Column('record_id', sa.String(length=128), nullable=True),
    sa.Column('scale_id', sa.String(length=32), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_index_composite_key'), 'score_index', ['composite_key'], unique=False)
    op.create_index(op.f('ix_score_index_cycle'), 'score_index', ['cycle'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('compare_lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=128), nullable=False),
    sa.Column('cycle', sa.String(length=8), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('position >= 0 AND position <= 3', name='ck_compare_slot_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'position', name='uq_compare_user_slot'),
    sa.UniqueConstraint('user_id', 'record_id', name='uq_compare_user_record')
    )
    op.create_index(op.f('ix_compare_lists_user_id'), 'compare_lists', ['user_id'], unique=False)
    op.create_table('filter_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('cycle', sa.String(length=8), nullable=False),
    sa.Column('view', sa.String(length=32), nullable=False),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('metric', sa.String(length=32), nullable=True),
    sa.Column('release', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_snapshots_user_id'), 'filter_snapshots', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_tokens_user_family', 'refresh_tokens', ['user_id', 'family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('saved_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=128), nullable=False),
    sa.Column('cycle', sa.String(length=8), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'record_id', name='uq_saved_user_record')
    )
    op.create_index(op.f('ix_saved_positions_user_id'), 'saved_positions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_positions_user_id'), table_name='saved_positions')
    op.drop_table('saved_positions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_family', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_filter_snapshots_user_id'), table_name='filter_snapshots')
    op.drop_table('filter_snapshots')
    op.drop_index(op.f('ix_compare_lists_user_id'), table_name='compare_lists')
    op.drop_table('compare_lists')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_score_index_cycle'), table_name='score_index')
    op.drop_index(op.f('ix_score_index_composite_key'), table_name='score_index')
    op.drop_table('score_index')
    op.drop_table('salary_data')
    op.drop_index(op.f('ix_review_events_severity'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_kind'), table_name='review_events')
    op.drop_table('review_events')
    op.drop_index(op.f('ix_jobs_lb'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_exam'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_cycle'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_code'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_city'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('cycles')
    # ### end Alembic commands ###
