"""0003 job exclusion evidence columns

Revision ID: 8327a515dc2e
Revises: c60604334732
Create Date: 2026-09-08 00:33:52.824516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8327a515dc2e'
down_revision: Union[str, None] = 'c60604334732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('exclusion_reason', sa.String(length=128), nullable=True))
    op.add_column('jobs', sa.Column('exclusion_evidence', sa.String(length=256), nullable=True))
    op.add_column('jobs', sa.Column('excluded_at', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'excluded_at')
    op.drop_column('jobs', 'exclusion_evidence')
    op.drop_column('jobs', 'exclusion_reason')
    # ### end Alembic commands ###
