"""0002 mirror state + job enhancements

Revision ID: c60604334732
Revises: 422c971fb1b1
Create Date: 2026-09-07 18:36:46.014565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60604334732'
down_revision: Union[str, None] = '422c971fb1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mirror_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cycle', sa.String(length=8), nullable=False),
    sa.Column('release', sa.String(length=64), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('job_id_set_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_rows', sa.Integer(), nullable=True),
    sa.Column('active_rows', sa.Integer(), nullable=True),
    sa.Column('recruits', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mirror_state_cycle'), 'mirror_state', ['cycle'], unique=True)
    op.add_column('jobs', sa.Column('bm', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('record_status', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_jobs_record_status'), 'jobs', ['record_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_record_status'), table_name='jobs')
    op.drop_column('jobs', 'record_status')
    op.drop_column('jobs', 'bm')
    op.drop_index(op.f('ix_mirror_state_cycle'), table_name='mirror_state')
    op.drop_table('mirror_state')
    # ### end Alembic commands ###
